hide_category_dropdown:
  default: true

hide_all_breadcrumb_nav:
  default: false

hide_on_topic_scroll:
  default: false
  refresh: true

links:
  type: objects
  default: []
  schema:
    name: link
    properties:
      link:
        type: string
        required: true
      label:
        type: string
        required: true
